### ISSUE TITLE
Please create a new release!

### ISSUE THREAD

**Issue by robbat2** [s3tools/s3cmd#814] opened 2016-12-20 20:20 UTC
It's been nearly a year since the last release :-(

**Comment by fviard** [comment] 2016-12-22 10:51
True, maybe we could be able to create a new one before reaching the year :-)

**Comment by josegonzalez** [comment] 2016-12-27 21:40
This would be ideal, as the current stable release does not support python3 (though master does) :)

**Comment by mdomsch** [comment] 2017-01-03 00:49
Master is broken on python3 again due to inclusion of the custom_httplib27
by ConnMan.py.

**Comment by MrChrisRodriguez** [comment] 2017-06-09 21:38
There are now 164 commits since the latest release almost a year and a half ago including many commits that fix non-obvious otherwise broken capabilities (like downloading multipart files when requester-pays is enabled).

What's the blocker on releasing 1.6.2? 

At this point it's likely better to release a version that doesn't support Python3 but solves myriad other problems than continue kicking the bucket down the road.

**Comment by fviard** [comment] 2017-06-09 21:58
@MrChrisRodriguez I promise that a release will come in not too long. Because of the python 3 important change, I did want to have some confidence that things were reliable enough. And indeed, there were some important issues that were fixed.
One major blocking point was having the auto tests being able to pass completely for py2 and py3.
That's now ok, even if there remain 2 strange random issues that made me lose a lot of time.

The real blocker is always the lack of time.
If you want to help, something that I would appreciate a lot is that if you can "shake" the thing to try to find any regression.

Btw, the good with the port to py3 is that it allowed to go over and clean a lot of things that should make the whole thing run better, even with py2.

**Comment by MrChrisRodriguez** [comment] 2017-06-09 22:02
Hi @fviard -- is there any area in particular that you're worried about? 

It's hard to prove the absence of something (like finding a regression if none are expected to exist) as opposed to knowing some acceptance criteria in advance that we can test for and, if they fail, repair against.

Is the auto-tests where we should be looking, or do you need those extended to cover additional mechanics?

**Comment by fviard** [comment] 2017-06-09 22:13
First, the most important is the kind of "commands" and parameters that you (-a standard person-) could be using. If some features are not so much used, that is not too worrying that it would be unexpectedly broken.

Then, the thing that worries me the much is the "combination" of source and targets.
ie:
from folder to folder/
from folder/ to folder/
from file to file
You see, all the combinations with a "/" or not at the end of a source or a destination.
And that mixed with "--delete" flags.
The goal being that there are no risk to accidentaly erase "users" data.
There is a good PR that has to be merged on this topic.

**Comment by fviard** [comment] 2017-06-27 12:03
Version 2.0.0 was released yesterday :-)

**Closed by fviard** 2017-06-27 12:03 UTC

**Comment by MrChrisRodriguez** [comment] 2017-06-27 14:06
CELEBRATION!!!! Congrats :-)
