### ISSUE TITLE
s3cmd sync doesn't detect remote files

### ISSUE THREAD

**Issue by obecker** [s3tools/s3cmd#660] opened 2015-11-12 12:27 UTC
Every time I'm running a `s3cmd sync . s3://www.***** --delete-removed --acl-public` command to sync my local files to a S3 bucket, it will upload all of my local files. Using the `--verbose`` flag outputs the following

```
INFO: Compiling list of local files...
INFO: Running stat() and reading/calculating MD5 values on 91 files, this may take some time...
INFO: Retrieving list of remote files for s3://www.*****/. ...
INFO: Found 91 local files, 0 remote files
INFO: Verifying attributes...
INFO: Summary: 49 local files to upload, 42 files to remote copy, 0 remote files to delete
```

I can run the command a second time and it will give the same info again and it will upload again all of the files.

Why does it say `0 remote files`?
I'm pretty sure this has worked properly in a previous version of s3cmd.

**Comment by frankcrawford** [comment] 2015-11-14 04:25
I'm also seeing this since upgrading from 1.5.1 to 1.6.0.  I'm just running s3cmd sync . s3://my-bucket/ and it has suddenly started trying to upload all the files rather than just the changed files.  
Running -v -d gives:

INFO: Retrieving list of remote files for s3://my-bucket/. ...
INFO: Forwarding request to ap-southeast-1
INFO: Found 290799 local files, 0 remote files
INFO: Verifying attributes...
INFO: Summary: 283556 local files to upload, 7243 files to remote copy, 0 remote files to delete

**Comment by frankcrawford** [comment] 2015-11-14 07:46
Okay, after some testing, I've found what the issue is, although I don't know what the difference is in the code.  It appears that 1.6 treats directories differently if the end in '/' or not.  So for my earlier issue:

s3cmd sync . s3://my-bucket/

doesn't match anything, but

s3cmd sync ./ s3://my-bucket/

works as previously, and matches fine.

In fact, now looking at the messages the issue makes sense, if appears that if the local source does not end in a '/' it is added to the destination bucket, but when it adds the lone `.' that is not a valid path in S3, hence no matches.

This appears to be different than for 1.5.1, where it didn't add the lone `.' or in fact any of the local source.

**Comment by fviard** [comment] 2015-11-14 18:24
@frankcrawford Thank you for your investigation. Is it possible for you to try the current master version of s3cmd? I did modify a lot of things related to the handling of "/".

**Comment by frankcrawford** [comment] 2015-11-15 08:05
Okay, I'll give it a go in the next day or two.
Frank

**Comment by obecker** [comment] 2015-11-19 08:06
Yes, adding a slash works for me too. Thanks a lot.

**Comment by frankcrawford** [comment] 2015-11-21 07:00
@fviard sorry for the delay.  I downloaded the latest version from version from here, and unfortunately, there was no difference, it still fails to match the directory if it is given as either "." or "/."

A quick look at the code shows that while there is special coding for ending in "/", there is nothing about "." or "/.".  I think it would probably be an easy fix (i.e. delete a trailing '.') I'm not sure I would find all the spots that may need it.

**Comment by ffernand** [comment] 2015-11-23 01:05
Please note that it also doesn't work if we're syncing just one file (no directory reference).

ie)  s3cmd sync /path/to/file.txt  s3://bucket/aa/bb/sha1_of_filename

**Comment by ab** [comment] 2015-12-16 22:43
:+1:

**Comment by thoys** [comment] 2016-02-10 15:36
:+1: got same bug  changing the local directory to `./` instead of `.` helped thanks @frankcrawford  !

**Comment by felixbuenemann** [comment] 2016-06-06 23:41
Same problem and the solution of `./` works. This should really be fixed, because it works quite different from other unix utilities.

**Comment by jrmiller82** [comment] 2016-08-05 20:55
+1 Just encountered this issue with s3cmd (Debian testing) `./` worked and `.` did not match.

**Comment by ComputerSmiths** [comment] 2016-09-14 20:10
And where:
s3cmd sync --recursive s3://bucket/dir/dir/ /mnt/dir/dir/dir/dir/
used to work, now I have to use
s3cmd sync --recursive s3://bucket/dir/dir /mnt/dir/dir/dir/dir/
(the trailing / on the S3 bucket directory results in:
INFO: Found 0 remote files, 27 local files
error)

**Comment by catalanojuan** [comment] 2016-09-27 19:04
+1 encountered the same issue on 1.6.0 (OS X 10.11.6)

**Comment by fviard** [comment] 2016-11-18 12:53
The main issue should already be fixed in master for some times.
And I did push an additional fix for the case of syncing a single file that was broken.

**Closed by fviard** 2016-11-18 12:53 UTC
Labels: to-be-fixed

**Comment by jtbr** [comment] 2018-05-13 21:35
The (remaining) difference from 1.5.* and later seems to be that any duplicate file *in the destination bucket* was not synced across previously (it would be copied remotely). Whereas now, this only works for files *in the destination folder* within the bucket. An exact remote copy of the file you wish to sync may exist, but will not be remotely copied (and instead will be uploaded) if it is not in your destination folder.
