### ISSUE TITLE
Error on s3cmd la or put (float argument required, not str)

### ISSUE THREAD

**Issue by Fuzi0n** [s3tools/s3cmd#427] opened 2014-11-28 19:42 UTC
Hi guys,

I encounter an error with swift3 and openstack swift while using some commands with s3cmd.

It works fine with "ls":

root@swiftnp01:~/download/source/s3cmd# ./s3cmd ls 
2009-02-03 16:45  s3://container
2009-02-03 16:45  s3://install-pkgs.log

But no luck with "la":

root@fleducquede-swiftnp01:~/download/source/s3cmd# ./s3cmd la s3://container
WARNING: Retrying failed request: /?delimiter=/ (float argument required, not str)
WARNING: Waiting 3 sec..

I googled that error and I've seen that you already fixed a similar bug: http://sourceforge.net/p/s3tools/bugs/134/

Can you help?

My CFG:
Ubuntu 12.04
openstack swift icehouse
swift3 (just git cloned it)
s3cmd (just git cloned it)

PS; I can copy/paste the debug log if u need it.

**Comment by mdomsch** [comment] 2015-02-04 14:15
I am not able to reproduce this with current master branch.  Closing.

**Closed by mdomsch** 2015-02-04 14:15 UTC
