### ISSUE TITLE
s3cmd put files from tar stdin: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by TrueShutDown** [s3tools/s3cmd#1127] opened 2020-08-26 00:13 UTC
I was trying to upload files from stdin by s3cmd, by this command below

`tar cfz - folder | s3cmd put - s3://backups/abcd.tar`

but sometimes I get ERROR

```
ERROR: Cannot retrieve any response status before encountering an EPIPE or ECONNRESET exception
WARNING: Upload failed: /abcd.tar?partNumber=21&uploadId=... ([Errno 32] Broken pipe)
WARNING: Waiting 3 sec...
```

I think s3cmd is waiting to long for TAR and Amazon S3 close connection

**Comment by fviard** [comment] 2020-08-31 23:23
Is it possible for you to test the latest MASTER version of s3cmd?
I think that this issue should be fixed with recent changes.
(Amazon is doing funky thing with short connection timeouts in some conditions)
Otherwise, the fixes should be available with the next release (>= 2.2.0)

**Comment by bradgranath2** [comment] 2021-04-09 23:36
I am also having this problem in 2.0.2, 2.1.0, installed with either apt or pip and 2.1.0+ (the current master version via the zip file on github).  I was able to make it go away by setting my multipart-chunk-size-mb=128

Any values higher than 128 result in the broken pipe error. values of 128 or less work fine.  It also works if I remove the option (because the default is 15mb)

I'm using digitalocean spaces instead of AWS, so the values may be irrelevant, but perhaps the option is significant in some way?

**Comment by canuckdev** [comment] 2021-05-05 17:39
Also having this problem consistently using DO spaces.
- s3cmd version 2.0.1
- multipart-chunk-size-mb=75
<pre>
upload: 'F1 2016/03 China 02.Race.Session.SD.mp4' -> 's3://bucket/vidcap/F1 2016/03 China 02.Race.Session.SD.mp4'  [part 18 of 23, 75MB] [2 of 56]
   524288 of 78643200     0% in   14s    35.47 kB/s  failed
ERROR: Cannot retrieve any response status before encountering an EPIPE or ECONNRESET exception
WARNING: Upload failed: /vidcap/F1%202016/03%20China%2002.Race.Session.SD.mp4?partNumber=18&uploadId=2~dD9pLHJSmLt3KnCztOxd9xnW2CJYAw_ ([Errno 32] Broken pipe)
WARNING: Retrying on lower speed (throttle=0.00)
WARNING: Waiting 3 sec...
upload: 'F1 2016/03 China 02.Race.Session.SD.mp4' -> 's3://bucket/vidcap/F1 2016/03 China 02.Race.Session.SD.mp4'  [part 18 of 23, 75MB] [2 of 56]
 78643200 of 78643200   100% in   65s  1173.53 kB/s  done
</pre>

**Comment by fviard** [comment] 2021-10-14 07:36
@aurisnoctis You can try to play with the 2 following parameters in the config:
```
connection_pooling = True
    # How long in seconds a connection can be kept idle in the pool and still
    # be alive. AWS s3 is supposed to close connections that are idle for 20
    # seconds or more, but in real life, undocumented, it closes https conns
    # after around 6s of inactivity.
    connection_max_age = 5
```

First you can try reducing the max_age to something like 1s, and if you are still encountering the issue, just disable the "reuse" of connections with `connection_pooling=False` .

Please let me know if it fixes you issue?

**Comment by fviard** [comment] 2021-10-14 11:37
No, it is different usage, and so different way to try to fix a similar
effect problem.

The bigger your chunk size, the more chance that there is a network or
server error and that you will have to retry. And in that case the whole
chunk.
But normally, if you network is not too bad, he hundreds of mb uploads
should be ok.

But sometimes, when the chunk is too big, the md5/processing time between 2
chunks could be too big for the server timeout between 2 requests.


On the other side, the two last variables control the fact that we reuse
connection after each request instead of losing time setting up a new
connection for each request.
The problem is that sometimes the server have too low timeout for
persisting connection between requests and so it closes them without
notifying us. So we will just fail at the next request when trying to send
it with the previous connection.

Sometimes, cheaper/crappy services could even not accept more than one
request per connection.

So, the thing is to try to understand in each case what is the behavior of
the server for reused connections and timeout. Sometimes it is in their
documentation. But other times like AWS, they have special undocumented
timeout for some endpoints but not all.

Le jeu. 14 oct. 2021 à 13:14, aurisnoctis ***@***.***> a
écrit :

**Closed** 2022-10-04 21:02 UTC
Labels: waiting-feedback
