### ISSUE TITLE
AttributeError: 'dict_keys' object has no attribute 'sort'

### ISSUE THREAD

**Issue by jesseorr** [s3tools/s3cmd#1133] opened 2020-09-29 18:14 UTC
ENV:
Invoked as: /usr/local/bin/s3cmd --recursive --skip-existing --files-from=test.txt sync . s3://redacted/
Problem: <class 'AttributeError: 'dict_keys' object has no attribute 'sort'
S3cmd:   2.1.0
python:   3.6.8 (default, Apr 16 2020, 01:36:27)
[GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
environment LANG=en_US.UTF-8

Getting an inability to run s3cmd utilizing python 3.6.8 on EL8. 
Tried s3cmd from python3-pip, as well as from yum/EPEL.

The root problem:
  File "/usr/local/lib/python3.6/site-packages/S3/FileLists.py", line 188, in _get_filelist_from_file
    keys.sort()
AttributeError: 'dict_keys' object has no attribute 'sort'

Adjusting code from:
```
186     result = []
187     keys = filelist.keys()
188     keys.sort()
189     for key in keys:
190         values = filelist[key]
191         values.sort()
192         result.append((key, [], values))
193     return result
194
```

to:
```
186     result = []
187     keys = list(filelist.keys())
188     keys.sort()
189     for key in keys:
190         values = filelist[key]
191         values.sort()
192         result.append((key, [], values))
193     return result
194
```

This however conflicts with the main branch in git, but does not appear to be functional for python3/s3cmd2.x.x despite the website noting that python3 support is available in version 2+.

Looking for long-term resolution, rather than my patched code on NN servers.

**Comment by fviard** [comment] 2021-05-02 20:20
In fact, a duplicate of #1101 .
So already fixed in MASTER.

**Closed by fviard** 2021-05-02 20:20 UTC
Labels: Duplicate
