### ISSUE TITLE
Log file [x of y] incorrect (still)

### ISSUE THREAD

**Issue by jamieburchell** [s3tools/s3cmd#522] opened 2015-04-05 13:25 UTC
This bug still seems to be present on 1.5.2:

E.g. (4 of 2):

```
Upgrade/PowerDVD_v5202_RiTA10(Patch)_Patch_DVD130415-01.exe' (143783408 bytes in 902.6 seconds, 155.56 kB/s) [4 of 2]
```

Full log:

```
INFO: Compiling list of local files...
INFO: Running stat() and reading/calculating MD5 values on 406 files, this may take some time...
INFO: Retrieving list of remote files for s3://xxx/Applications/ ...
INFO: Found 406 local files, 403 remote files
INFO: Verifying attributes...
INFO: Summary: 3 local files to upload, 2 files to remote copy, 2 remote files to delete
INFO: Sending file '/share/Applications/PowerDVD/CyberLink_PowerDVD14_Pro_DVD140826-02.exe', please wait...
INFO: Sending file '/share/Applications/PowerDVD/CyberLink_PowerDVD14_Pro_DVD140826-02.exe', please wait...
INFO: Sending file '/share/Applications/PowerDVD/CyberLink_PowerDVD14_Pro_DVD140826-02.exe', please wait...
INFO: Sending file '/share/Applications/PowerDVD/CyberLink_PowerDVD14_Pro_DVD140826-02.exe', please wait...
INFO: Sending file '/share/Applications/PowerDVD/CyberLink_PowerDVD14_Pro_DVD140826-02.exe', please wait...
INFO: Sending file '/share/Applications/PowerDVD/CyberLink_PowerDVD14_Pro_DVD140826-02.exe', please wait...
INFO: Sending file '/share/Applications/PowerDVD/CyberLink_PowerDVD14_Pro_DVD140826-02.exe', please wait...
INFO: Sending file '/share/Applications/PowerDVD/CyberLink_PowerDVD14_Pro_DVD140826-02.exe', please wait...
INFO: Sending file '/share/Applications/PowerDVD/CyberLink_PowerDVD14_Pro_DVD140826-02.exe', please wait...
INFO: Sending file '/share/Applications/PowerDVD/CyberLink_PowerDVD14_Pro_DVD140826-02.exe', please wait...
File '/share/Applications/PowerDVD/CyberLink_PowerDVD14_Pro_DVD140826-02.exe' stored as 's3://xxx/Applications/PowerDVD/CyberLink_PowerDVD14_Pro_DVD140826-02.exe' (148192560 bytes in 802.3 seconds, 180.38 kB/s) [1 of 3]
INFO: Sending file '/share/Applications/PowerDVD/PowerDVD_14.0.4704.58_Patch_DVD140911-04.exe', please wait...
INFO: Sending file '/share/Applications/PowerDVD/PowerDVD_14.0.4704.58_Patch_DVD140911-04.exe', please wait...
INFO: Sending file '/share/Applications/PowerDVD/PowerDVD_14.0.4704.58_Patch_DVD140911-04.exe', please wait...
INFO: Sending file '/share/Applications/PowerDVD/PowerDVD_14.0.4704.58_Patch_DVD140911-04.exe', please wait...
INFO: Sending file '/share/Applications/PowerDVD/PowerDVD_14.0.4704.58_Patch_DVD140911-04.exe', please wait...
INFO: Sending file '/share/Applications/PowerDVD/PowerDVD_14.0.4704.58_Patch_DVD140911-04.exe', please wait...
INFO: Sending file '/share/Applications/PowerDVD/PowerDVD_14.0.4704.58_Patch_DVD140911-04.exe', please wait...
INFO: Sending file '/share/Applications/PowerDVD/PowerDVD_14.0.4704.58_Patch_DVD140911-04.exe', please wait...
INFO: Sending file '/share/Applications/PowerDVD/PowerDVD_14.0.4704.58_Patch_DVD140911-04.exe', please wait...
INFO: Sending file '/share/Applications/PowerDVD/PowerDVD_14.0.4704.58_Patch_DVD140911-04.exe', please wait...
File '/share/Applications/PowerDVD/PowerDVD_14.0.4704.58_Patch_DVD140911-04.exe' stored as 's3://xxx/Applications/PowerDVD/PowerDVD_14.0.4704.58_Patch_DVD140911-04.exe' (148100944 bytes in 781.6 seconds, 185.04 kB/s) [2 of 3]
INFO: Sending file '/share/Applications/PowerDVD/key.txt', please wait...
File '/share/Applications/PowerDVD/key.txt' stored as 's3://xxx/Applications/PowerDVD/key.txt' (35 bytes in 0.2 seconds, 223.45 B/s) [3 of 3]
ERROR: S3 error: Operation is not valid for the source object's storage class
WARNING: Unable to remote copy files s3://xxx/Applications/PowerDVD 10 Upgrade/PowerDVD_v5202_RiTA10(Patch)_Patch_DVD130415-01.exe -> s3://xxx/Applications/@Recycle/PowerDVD 10 Upgrade/PowerDVD_v5202_RiTA10(Patch)_Patch_DVD130415-01.exe
ERROR: S3 error: Operation is not valid for the source object's storage class
WARNING: Unable to remote copy files s3://xxx/Applications/PowerDVD 10 Upgrade/TSST.v4126_RiTA10(AW_DVD121025-01.exe -> s3://xxx/Applications/@Recycle/PowerDVD 10 Upgrade/TSST.v4126_RiTA10(AW_DVD121025-01.exe
INFO: Sending file '/share/Applications/@Recycle/PowerDVD 10 Upgrade/PowerDVD_v5202_RiTA10(Patch)_Patch_DVD130415-01.exe', please wait...
INFO: Sending file '/share/Applications/@Recycle/PowerDVD 10 Upgrade/PowerDVD_v5202_RiTA10(Patch)_Patch_DVD130415-01.exe', please wait...
INFO: Sending file '/share/Applications/@Recycle/PowerDVD 10 Upgrade/PowerDVD_v5202_RiTA10(Patch)_Patch_DVD130415-01.exe', please wait...
INFO: Sending file '/share/Applications/@Recycle/PowerDVD 10 Upgrade/PowerDVD_v5202_RiTA10(Patch)_Patch_DVD130415-01.exe', please wait...
INFO: Sending file '/share/Applications/@Recycle/PowerDVD 10 Upgrade/PowerDVD_v5202_RiTA10(Patch)_Patch_DVD130415-01.exe', please wait...
INFO: Sending file '/share/Applications/@Recycle/PowerDVD 10 Upgrade/PowerDVD_v5202_RiTA10(Patch)_Patch_DVD130415-01.exe', please wait...
INFO: Sending file '/share/Applications/@Recycle/PowerDVD 10 Upgrade/PowerDVD_v5202_RiTA10(Patch)_Patch_DVD130415-01.exe', please wait...
INFO: Sending file '/share/Applications/@Recycle/PowerDVD 10 Upgrade/PowerDVD_v5202_RiTA10(Patch)_Patch_DVD130415-01.exe', please wait...
WARNING: Upload failed: /Applications/@Recycle/PowerDVD%2010%20Upgrade/PowerDVD_v5202_RiTA10(Patch)_Patch_DVD130415-01.exe?partNumber=8&uploadId=Ice90sWx6lVyQeTvvfTQkfJt_CMW9H8OQ6G5.WhDFP81QHodhjQAXHEzYG_4GUUJ0bfMdXVHb1l7YFSkIH0SAK9phLKxoLUO6MsUKmrpyTajj8M5zXboeEL7gLssDjdJ ([Errno 104] Connection reset by peer)
WARNING: Retrying on lower speed (throttle=0.00)
WARNING: Waiting 3 sec...
INFO: Sending file '/share/Applications/@Recycle/PowerDVD 10 Upgrade/PowerDVD_v5202_RiTA10(Patch)_Patch_DVD130415-01.exe', please wait...
INFO: Sending file '/share/Applications/@Recycle/PowerDVD 10 Upgrade/PowerDVD_v5202_RiTA10(Patch)_Patch_DVD130415-01.exe', please wait...
INFO: Sending file '/share/Applications/@Recycle/PowerDVD 10 Upgrade/PowerDVD_v5202_RiTA10(Patch)_Patch_DVD130415-01.exe', please wait...
File '/share/Applications/@Recycle/PowerDVD 10 Upgrade/PowerDVD_v5202_RiTA10(Patch)_Patch_DVD130415-01.exe' stored as 's3://xxx/Applications/@Recycle/PowerDVD 10 Upgrade/PowerDVD_v5202_RiTA10(Patch)_Patch_DVD130415-01.exe' (143783408 bytes in 902.6 seconds, 155.56 kB/s) [4 of 2]
INFO: Sending file '/share/Applications/@Recycle/PowerDVD 10 Upgrade/TSST.v4126_RiTA10(AW_DVD121025-01.exe', please wait...
INFO: Sending file '/share/Applications/@Recycle/PowerDVD 10 Upgrade/TSST.v4126_RiTA10(AW_DVD121025-01.exe', please wait...
INFO: Sending file '/share/Applications/@Recycle/PowerDVD 10 Upgrade/TSST.v4126_RiTA10(AW_DVD121025-01.exe', please wait...
INFO: Sending file '/share/Applications/@Recycle/PowerDVD 10 Upgrade/TSST.v4126_RiTA10(AW_DVD121025-01.exe', please wait...
INFO: Sending file '/share/Applications/@Recycle/PowerDVD 10 Upgrade/TSST.v4126_RiTA10(AW_DVD121025-01.exe', please wait...
INFO: Sending file '/share/Applications/@Recycle/PowerDVD 10 Upgrade/TSST.v4126_RiTA10(AW_DVD121025-01.exe', please wait...
INFO: Sending file '/share/Applications/@Recycle/PowerDVD 10 Upgrade/TSST.v4126_RiTA10(AW_DVD121025-01.exe', please wait...
INFO: Sending file '/share/Applications/@Recycle/PowerDVD 10 Upgrade/TSST.v4126_RiTA10(AW_DVD121025-01.exe', please wait...
File '/share/Applications/@Recycle/PowerDVD 10 Upgrade/TSST.v4126_RiTA10(AW_DVD121025-01.exe' stored as 's3://xxx/Applications/@Recycle/PowerDVD 10 Upgrade/TSST.v4126_RiTA10(AW_DVD121025-01.exe' (119733672 bytes in 658.7 seconds, 177.52 kB/s) [5 of 2]
File s3://xxx/Applications/PowerDVD 10 Upgrade/PowerDVD_v5202_RiTA10(Patch)_Patch_DVD130415-01.exe deleted
File s3://xxx/Applications/PowerDVD 10 Upgrade/TSST.v4126_RiTA10(AW_DVD121025-01.exe deleted
Done. Uploaded 559810619 bytes in 3146.2 seconds, 173.76 kB/s. Copied 2 files saving 0 bytes transfer.
```

Possibly this happens when a multi-part file fails to upload or if a remote copy can't happen on a Glacier object?

Cheers
Jamie

**Comment by fviard** [comment] 2015-04-14 12:40
Hi,
Have you tested with the current version in github? It should be fixed in current code.
I have done a fix for that a little after the release of the version 1.5.2 i think.

The issue is that s3cmd first try to remote copy 2 files as an optimization, but that is not possible because of the storage class of the possible source of the copies ("ERROR: S3 error: Operation is not valid for the source object's storage class").
So, s3cmd will retry at the end with a real upload, but the progress info was previously broken in that case.

**Comment by jamieburchell** [comment] 2015-04-14 16:55
Hey
Not tried on the master version yet...
Cheers
Jamie

**Closed** 2015-11-04 01:02 UTC
