### ISSUE TITLE
Error parsing xml: not well-formed (invalid token): line 1, column 1

### ISSUE THREAD

**Issue by xingxing122** [s3tools/s3cmd#866] opened 2017-05-05 06:02 UTC
s3cmd setacl --acl-public s3://test01/a.txt 
ERROR: Error parsing xml: not well-formed (invalid token): line 1, column 1
ERROR: ## test  

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
  If the error persists, please report the
  following lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Invoked as: /usr/bin/s3cmd setacl --acl-public s3://test01/a.txt
Problem: ParseError: not well-formed (invalid token): line 1, column 1
S3cmd:   1.6.1
python:   2.7.5 (default, Nov  6 2016, 00:28:07) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
environment LANG=en_US.UTF-8

Traceback (most recent call last):
  File "/usr/bin/s3cmd", line 2919, in <module>
    rc = main()
  File "/usr/bin/s3cmd", line 2841, in main
    rc = cmd_func(args)
  File "/usr/bin/s3cmd", line 1836, in cmd_setacl
    update_acl(s3, uri, seq_label)
  File "/usr/bin/s3cmd", line 2402, in update_acl
    acl = s3.get_acl(uri)
  File "/usr/lib/python2.7/site-packages/S3/S3.py", line 837, in get_acl
    acl = ACL(response['data'])
  File "/usr/lib/python2.7/site-packages/S3/ACL.py", line 82, in __init__
    tree = getTreeFromXml(xml)
  File "/usr/lib/python2.7/site-packages/S3/Utils.py", line 89, in getTreeFromXml
    tree = ET.fromstring(xml)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 1, column 1

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
  If the error persists, please report the
  above lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by DavidGoodwin** [comment] 2019-10-19 09:50
I'm seeing the same, probably due to a file name containing weird unicode characters.

```
WARNING: 1 non-printable characters replaced in: htdocs/wp-content/uploads/2016/02/CHATEAU-CABEZAC-LA-TRADITION-ROSEâ€™-2011-MINERVOIS-FRANCE^K.jpg
```

and then 

```
ERROR: Error parsing xml: reference to invalid character number: line 2, column 179754
ERROR: <?xml version="1.0" encoding="UTF-8"?>
<ListBucketResult><Name>some-backup-bucket</Name><Prefix>sites/k/knottedvine/</Prefix><Marker>sites/k/foobar/htdocs/wp-content/uploads/2015/11/italy-cossetti.jpg</Marker><MaxKeys>1000</MaxKeys><IsTruncated>true</IsTruncated><Contents><Key>....
```

```
% s3cmd --version
s3cmd version 1.6.1
```

(via Debian Jessie backports - 1.6.1-1~bpo8+1 )

**Comment by fviard** [comment] 2020-03-29 01:23
I think that it is already fixed in MASTER as I'm not able to reproduce the issue.
Please reopen if you are still encountering it with the next release (> 2.0.2). thanks

**Closed by fviard** 2020-03-29 01:23 UTC
