### ISSUE TITLE
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 94

### ISSUE THREAD

**Issue by rmanus** [s3tools/s3cmd#1241] opened 2022-03-10 11:52 UTC
```
ERROR: Error parsing xml: not well-formed (invalid token): line 1, column 94
ERROR: b'<?xml version="1.0" encoding="UTF-8"?><ListBucketResult><Name>jfp000ew80</Name><Prefix>Public/\xef\xbf\xbf/</Prefix><MaxKeys>1000</MaxKeys><IsTruncated>false</IsTruncated><Marker/></ListBucketResult>'

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions-(FAQ)
  If the error persists, please report the
  following lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Invoked as: /usr/local/bin/s3cmd sync --preserve --multipart-chunk-size-mb 128 --delete-removed --force --no-check-md5 --rexclude ^\. --rexclude \/\. --rexclude ^\~ --rexclude \/\~ Public/￿/ cloud://Public/￿/
Problem: ParseError: not well-formed (invalid token): line 1, column 94
S3cmd:   2.2.0
python:   3.7.3 (default, Jan 22 2021, 20:04:44) 
[GCC 8.3.0]
environment LANG=en_US.UTF-8

Traceback (most recent call last):
  File "/usr/local/bin/s3cmd", line 3209, in <module>
    rc = main()
  File "/usr/local/bin/s3cmd", line 3106, in main
    rc = cmd_func(args)
  File "/usr/local/bin/s3cmd", line 1965, in cmd_sync
    return cmd_sync_local2remote(args)
  File "/usr/local/bin/s3cmd", line 1932, in cmd_sync_local2remote
    ret = _single_process(args[:-1])
  File "/usr/local/bin/s3cmd", line 1682, in _single_process
    return _child(destination_base, source_args)
  File "/usr/local/bin/s3cmd", line 1791, in _child
    remote_list, dst_exclude_list, remote_total_size = fetch_remote_list(destbase_with_source_list, recursive = True, require_attribs = True)
  File "/usr/local/lib/python3.7/dist-packages/S3/FileLists.py", line 470, in fetch_remote_list
    objectlist, tmp_total_size = _get_filelist_remote(uri, recursive = True)
  File "/usr/local/lib/python3.7/dist-packages/S3/FileLists.py", line 407, in _get_filelist_remote
    recursive = recursive, uri_params = uri_params)
  File "/usr/local/lib/python3.7/dist-packages/S3/S3.py", line 333, in bucket_list
    for truncated, dirs, objects in self.bucket_list_streaming(bucket, prefix, recursive, uri_params, limit):
  File "/usr/local/lib/python3.7/dist-packages/S3/S3.py", line 369, in bucket_list_streaming
    current_list = _get_contents(response["data"])
  File "/usr/local/lib/python3.7/dist-packages/S3/S3.py", line 351, in _get_contents
    return getListFromXml(data, "Contents")
  File "/usr/local/lib/python3.7/dist-packages/S3/BaseUtils.py", line 277, in getListFromXml
    tree = getTreeFromXml(xml)
  File "/usr/local/lib/python3.7/dist-packages/S3/BaseUtils.py", line 265, in getTreeFromXml
    tree = ET.fromstring(xml)
  File "/usr/lib/python3.7/xml/etree/ElementTree.py", line 1315, in XML
    parser.feed(text)
  File "<string>", line None
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 94

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions-(FAQ)
  If the error persists, please report the
  above lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


```

**Comment by fviard** [comment] 2022-07-02 12:14
I can see in your command the following path "Public/�/" meaning that the character between slashes was not valid unicode.

And we can see from the server that the returned xml contains the following key:
</Name><Prefix>Public/\xef\xbf\xbf/</Prefix>

\xef \xbf \xbf is not a valid unicode character, so that means you used in your command line is probably wrong

https://www.fileformat.info/info/unicode/char/ffff/index.htm

Closing as it is not a bug of s3cmd, but don't hesitate to reopen if you have more element or disagree.

**Closed by fviard** 2022-07-02 12:14 UTC
