### ISSUE TITLE
403 (SignatureDoesNotMatch) error when specifies host with 80 port

### ISSUE THREAD

**Issue by Guoozz** [s3tools/s3cmd#1059] opened 2019-11-14 06:59 UTC
version: v2.0.2

when I run the followed cmd(host with 80 port), error has ocuured.
```bash
s3cmd --debug --no-ssl --access_key=AKIAIOSFODNN7EXAMPLE --secret_key=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY --host=10.10.40.90:80 --host-bucket= ls s3://cluster-001 
```

[s3.txt](https://github.com/s3tools/s3cmd/files/3844996/s3.txt)

```bash
s3cmd --debug --no-ssl --access_key=AKIAIOSFODNN7EXAMPLE --secret_key=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY --host=10.10.40.90 --host-bucket= ls s3://cluster-001 
```
but when I remove 80 port from host, everything is fine.
[success.txt](https://github.com/s3tools/s3cmd/files/3844998/success.txt)

**Comment by lanya16** [comment] 2019-11-28 06:29
I meet the same problem also

**Comment by Fengjina** [comment] 2020-01-17 07:29
the same problem with you

**Comment by fviard** [comment] 2020-03-19 18:03
Thanks for the report.
In fact, it is not a bug of s3cmd, but a issue with Minio, that I guess you were all using?
Let me redirect you instead to this new issue in Minio project about that problem.
(As it is there that it should be fixed or not)
https://github.com/minio/minio/issues/9169

**Comment by fviard** [comment] 2020-03-20 16:19
Looks like that Minio is defective because of Go, and that aws s3 is also affected.

**Closed** 2020-03-20 16:32 UTC

**Comment by Fengjina** [comment] 2020-03-26 02:23
thank you for your reply, but the ceph version I used is Nautilus. Does nautilus has this issue?



At 2020-03-20 02:03:56, "Florent Viard" <notifications@github.com> wrote:

Thanks for the report.
In fact, it is not a bug of s3cmd, but a issue with Minio, that I guess you were all using?
Let me redirect you instead to this new issue in Minio project about that problem.
(As it is there that it should be fixed or not)
minio/minio#9169

**Comment by fviard** [comment] 2020-03-26 02:30
@Fengjina Probably. Sadly, It looks like that a lot of servers do that.
So, finally, I pushed a fix to handle that case in s3cmd.
If you can't use/test, the last master branch of git, I will do a new release in the coming days.
