### ISSUE TITLE
I/O operation on closed file

### ISSUE THREAD

**Issue by TheRoSS** [s3tools/s3cmd#794] opened 2016-10-14 10:04 UTC
I am trying to download file from s3 and pipe it to xz decompression

```
$ s3cmd -q get s3://mybacket/myfile.xz - | xz -d
```

and get following error

```
WARNING: Retrying failed request: /archiveHistory/pi/type/2016/05/04/type-.user.login.log.xz (I/O operation on closed file)
WARNING: Waiting 3 sec...
```

Redirection to /dev/null also generates this error

```
$ s3cmd -q get s3://mybacket/myfile.xz - > /dev/null
```

I think this is because -q parameter suppress content output too.
But without -q the s3cmd writes to stdout its own info messages and xz fails

```
$ s3cmd get s3://mybacket/myfile.xz -
download: 's3://mybacket/myfile.xz' -> '-'
...
```

The 1.5.2 version did not written info message to stdout and decompression works

OS: Ubuntu 16.04.1 LTS
s3cmd: 1.6.1
python: 2.7.12
python3: 3.5.2

**Comment by llonergan** [comment] 2016-10-28 05:27
Hey - I also ran into this problem - you can work around it by using "--no-progress" instead of "-q"

**Comment by fviard** [comment] 2016-11-16 23:10
It should already be fixed in Master.
Is it possible for you to give it a try?
I'm not able to reproduce your issue anymore.

**Closed by fviard** 2016-11-16 23:10 UTC
