### ISSUE TITLE
--list-md5 causes 403 error

### ISSUE THREAD

**Issue by lowsky13** [s3tools/s3cmd#664] opened 2015-11-19 18:01 UTC
I'm having the same issue as this:
https://github.com/s3tools/s3cmd/issues/274

Basically, 
s3cmd ls --list-md5 --config=backup.cfg s3://mybucket/mydir/ will list files and their hashes successfully but then it says:
ERROR: S3 error: 403 (Forbidden)

That happens to be the last file in the bucket so I'm not sure if it stopped there or all the files were listed out and then the error at the end. I noticed the last file is also a really large file and the transfer-encoding is chunked.

If I remove the --list-md5 it works just fine with no error.

my s3cmd is the latest as of this morning: commit 04d7732f2671acb1aeb10e81bf87bfd0b068b6c5 and Ihis was a problem with version 1.52 as well.

I'm having this issue pushing to us-east-1 as well as Germany.

**Comment by mdomsch** [comment] 2015-12-08 15:41
Can you run with --debug?  I am not seeing a failure with current HEAD in us-east-1.

**Comment by fviard** [comment] 2016-11-18 12:55
Closing because of no more feedback.
Please re-open with a debug trace (-d) if still reproducible with latest master

**Closed by fviard** 2016-11-18 12:55 UTC
