### ISSUE TITLE
WARNING: Empty object name on S3 found, ignoring.

### ISSUE THREAD

**Issue by ezmiller** [s3tools/s3cmd#398] opened 2014-10-11 11:09 UTC
I'm getting this error message and am not sure exactly how to interpret it:

> WARNING: Empty object name on S3 found, ignoring.

Anyone know what it means? How to fix?

**Comment by silyevsk** [comment] 2015-01-21 11:44
:+1:

**Comment by rockmyrun** [comment] 2015-02-26 23:13
I am having this issue now too. Our servers just updated s3cmd from epel to this version:
s3cmd-1.5.1.2-5.el6

And we get this Error now every time s3cmd sync runs. I can output all errors to /dev/null to get rid of the cron job emails but then we miss any actual errors.

Is there any other fix for this?

**Comment by fviard** [comment] 2015-03-13 10:38
If you are still experiencing such an issue, could you run the last git version with the "--debug" flag?
So we can see what is returned by the server that triggers this?

**Comment by tilghman** [comment] 2016-04-11 18:44
Is version 1.6.0 sufficient for the debug?
[s3sync-debug-images.gz](https://github.com/s3tools/s3cmd/files/213650/s3sync-debug-images.gz)

**Comment by fviard** [comment] 2022-10-03 23:27
Closing as duplicate of #349

**Closed by fviard** 2022-10-03 23:27 UTC
Labels: Duplicate
