### ISSUE TITLE
Bug in current release 2.1.0 (AWS CREDENTIALS file broken)

### ISSUE THREAD

**Issue by snapfin-git** [s3tools/s3cmd#1102] opened 2020-05-12 19:32 UTC
Hi there, 

For the current release v2.1.0 the line 301 is broken which prevents the remainder of the code from being processed.  e is not defined.

warning("Errno %d accessing credentials file %s" % (e.errno, aws_credential_file))

This has been rectified in the current codebase in master branch.  Requesting a new release be cut from the latest on master.  This lib is rendered useless for people who are using aws credentials file in production environments and just need the tar file, unless they are willing to git clone the latest and create their own package.

Your help is appreciated.

Thanks.

**Comment by fviard** [comment] 2020-05-31 23:25
Thanks for your report.
Indeed this bug is a duplicate of #1094 that was already fixed in MASTER but not yet released.
So far, this fix will be included in the next release 2.2.0 that should not take too long to come.
I did not think that too many persons would be in such a situation, otherwise I would have released a minor release with it.
Sorry for the inconvenience.

**Closed by fviard** 2020-05-31 23:25 UTC
Labels: Duplicate

**Comment by rostislav-simonik-plc** [comment] 2020-08-01 07:35
@fviard is it possible to release only patch version. This is really unpleasant issue. We are using those environment variables, because .s3cfg is quite difficult to use in our setup. Many thanks.
