### ISSUE TITLE
AmazonS3 Header Error: SignatureDoesNotMatch

### ISSUE THREAD

**Issue by dsbcpas** [s3tools/s3cmd#491] opened 2015-03-07 20:00 UTC
s3cmd version 1.5.2 (from master branch on Feb 28th, 2015).
1 small unusual file of 70,000 will not "put" nor "sync" and throws this error.  
Seems to me that it's the content of the file and its suffix causing the problem.

Excerpts of applicable debug statements indicates a content-type error? The file is too old to be xml as indicated. It's used in an older application.

Interestingly:
1. When the error is encountered during a sync, the entire sync is aborted, not just this file.
2. If I specify --mime-type=image/jpeg it uploads without an error (it's not a jpeg file.)

DEBUG: Response: {'status': 403, 'headers': {'x-amz-id-2': ' [coding deleted]', 'server': 'AmazonS3', 'transfer-encoding': 'chunked', 'connection': 'close', 'x-amz-request-id': '[coding deleted]', 'date': 'Sat, 07 Mar 2015 17:12:40 GMT', 'content-type': 'application/xml'}, 'reason': 'Forbidden', 'data': '<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.

**Comment by mdomsch** [comment] 2015-03-07 20:12
please paste the debug info that precedes the 403 error being reported, in
particular the Canonical Request and headers being sent.

Thanks,
Matt

**Comment by dsbcpas** [comment] 2015-03-07 20:41
Here is the whole of it with privacy items deleted in the format of [coding deleted]

DEBUG: canonical_headers = content-length:512
content-type:F            0x07           video/h264
host:[coding deleted].s3.amazonaws.com
x-amz-content-sha256:[coding deleted]
x-amz-date:20150307T202728Z
x-amz-meta-s3cmd-attrs:uid:500/gname:users/uname:admin/gid:100/mode:33272/mtime:927044984/atime:1425760033/md5:eaeea348f226375afd0c07fcc30db491/cti$
x-amz-server-side-encryption:AES256
x-amz-storage-class:REDUCED_REDUNDANCY

DEBUG: Canonical Request:
PUT
/[coding deleted]%3A[coding deleted]/fileprefix.MRP

content-length:512
content-type:F            0x07           video/h264
host:[coding deleted].s3.amazonaws.com
x-amz-content-sha256:[coding deleted]
x-amz-date:20150307T202728Z
x-amz-meta-s3cmd-attrs:uid:500/gname:users/uname:admin/gid:100/mode:33272/mtime:927044984/atime:1425760033/md5:eaeea348f226375afd0c07fcc30db491/cti$
x-amz-server-side-encryption:AES256
x-amz-storage-class:REDUCED_REDUNDANCY

content-length;content-type;host;x-amz-content-sha256;x-amz-date;x-amz-meta-s3cmd-attrs;x-amz-server-side-encryption;x-amz-storage-class
e[coding deleted]
DEBUG: signature-v4 headers: {'x-amz-content-sha256': 'e[coding deleted]', 'content-length': 512, 'x$
DEBUG: Unicodising '' using UTF-8
DEBUG: Unicodising '' using UTF-8
DEBUG: CreateRequest: resource[uri]=/?location
DEBUG: Using signature v4
DEBUG: get_hostname([coding deleted]): [coding deleted].s3.amazonaws.com
DEBUG: canonical_headers = host:[coding deleted].s3.amazonaws.com
x-amz-content-sha256:e[coding deleted]
x-amz-date:20150307T202728Z

DEBUG: Canonical Request:
GET
/
location=
host:[coding deleted].s3.amazonaws.com
x-amz-content-sha256:e[coding deleted]
x-amz-date:20150307T202728Z

host;x-amz-content-sha256;x-amz-date
e[coding deleted]
----------------------
DEBUG: signature-v4 headers: {'x-amz-content-sha256': 'e[coding deleted]', 'Authorization': 'AWS4-HM$
DEBUG: Processing request, please wait...
DEBUG: get_hostname([coding deleted]): [coding deleted].s3.amazonaws.com
DEBUG: ConnMan.get(): creating new connection: https://[coding deleted].s3.amazonaws.com
DEBUG: Using ca_certs_file None
DEBUG: non-proxied HTTPSConnection([coding deleted].s3.amazonaws.com)
DEBUG: format_uri(): /?location
DEBUG: Sending request method_string='GET', uri='/?location', headers={'x-amz-content-sha256': 'e[coding deleted]$
DEBUG: Response: {'status': 200, 'headers': {'x-amz-id-2': '3[coding deleted]', 'server': 'AmazonS3'$
DEBUG: ConnMan.put(): connection put back to pool (https://[coding deleted].s3.amazonaws.com#1)
DEBUG: Using signature v4
DEBUG: get_hostname([coding deleted]): [coding deleted].s3.amazonaws.com
DEBUG: canonical_headers = content-length:512
content-type:F            0x07           video/h264
host:[coding deleted].s3.amazonaws.com
x-amz-content-sha256:a[coding deleted]
x-amz-date:20150307T202728Z
x-amz-meta-s3cmd-attrs:uid:500/gname:users/uname:admin/gid:100/mode:33272/mtime:927044984/atime:1425760033/md5:eaeea348f226375afd0c07fcc30db491/cti$
x-amz-server-side-encryption:AES256
x-amz-storage-class:REDUCED_REDUNDANCY

DEBUG: Canonical Request:
PUT
/[coding deleted]/filenameprefix.MRP

content-length:512
content-type:F            0x07           video/h264
host:[coding deleted].s3.amazonaws.com
x-amz-content-sha256:a[coding deleted]
x-amz-date:20150307T202728Z
x-amz-meta-s3cmd-attrs:uid:500/gname:users/uname:admin/gid:100/mode:33272/mtime:927044984/atime:1425760033/md5:eaeea348f226375afd0c07fcc30db491/cti$
x-amz-server-side-encryption:AES256
x-amz-storage-class:REDUCED_REDUNDANCY

content-length;content-type;host;x-amz-content-sha256;x-amz-date;x-amz-meta-s3cmd-attrs;x-amz-server-side-encryption;x-amz-storage-class
a[coding deleted]
----------------------
DEBUG: signature-v4 headers: {'x-amz-content-sha256': 'a[coding deleted]', 'content-length': 512, 'x$
DEBUG: get_hostname([coding deleted]): [coding deleted].s3.amazonaws.com
DEBUG: ConnMan.get(): re-using connection: https://[coding deleted].s3.amazonaws.com#1
DEBUG: format_uri(): /[coding deleted]/filenameprfix.MRP
DEBUG: ConnMan.put(): connection put back to pool (https://[coding deleted].s3.amazonaws.com#2)
DEBUG: Response: {'status': 403, 'headers': {'x-amz-id-2': 'P[coding deleted]W', 'server': 'AmazonS3'$
ERROR: S3 error: The request signature we calculated does not match the signature you provided. Check your key and signing method.

**Comment by mdomsch** [comment] 2015-04-01 21:08
Thanks.  There's nothing obvious as to why this would be failing from this though. :-(

**Comment by jamiejackson** [comment] 2015-04-17 21:32
How about this? I'm using the Git master (1.5.2), but it's still giving the same problem as the one from CentOS 7 repos (1.5.1.2):

```
[hudx_report_sync@vnuchx7hudftpcl bin]$ s3cmd modify --acl-public --no-preserve --reduced-redundancy --recursive s3://mybucket/reports/conplans/
WARNING: Empty object name on S3 found, ignoring.
File s3://mybucket/reports/conplans/1212201303281244AAP00STATE000000000000425000000000000425824848162XXXXMASSACHUSETTSMA.docx modified
File s3://mybucket/reports/conplans/20102010201408061518AAPCPLCLGV000000000009282000000000009282969035203XXXXALTOONAPA.docx modified
File s3://mybucket/reports/conplans/20102014201408061518CONPLLCLGV000000000009282000000000009282969035203XXXXALTOONAPA.docx modified
File s3://mybucket/reports/conplans/20112011201205151122AAP00LCLGV000000000043571000000000043571075814608XXXXITHACANY.docx modified
File s3://mybucket/reports/conplans/20112011201206251642AAP00LCLGV000000000030634000000000030634064772721XXXXRIVERSIDE+COUNTYCA.docx modified
File s3://mybucket/reports/conplans/20112011201206261546AAP00UNDEF000000000000119000000000000119854990462XXXXAMERICAN+SAMOAAS.docx modified
File s3://mybucket/reports/conplans/20112011201207121118AAP00LCLGV000000000003196000000000003196083782953XXXXCLARK+COUNTYNV.docx modified
File s3://mybucket/reports/conplans/20112011201207131622AAP00LCLGV000000000003451000000000003451077701647XXXXHONOLULUHI.docx modified
File s3://mybucket/reports/conplans/20112011201207161722AAP00LCLGV000000000001462000000000001462076529924XXXXBERKELEYCA.docx modified
File s3://mybucket/reports/conplans/20112011201207180942AAP00LCLGV000000000027370000000000027370002465805XXXXROCHESTERNY.docx modified
File s3://mybucket/reports/conplans/20112011201207231113AAP00LCLGV000000000009282000000000009282969035203XXXXALTOONAPA.docx modified
File s3://mybucket/reports/conplans/20112011201207261138AAP00STATE000000000000476000000000000476809037120XXXXMICHIGANMI.docx modified
File s3://mybucket/reports/conplans/20112011201207261234AAP00LCLGV000000000026758000000000026758010919447XXXXSALINASCA.docx modified
ERROR: S3 error: The request signature we calculated does not match the signature you provided. Check your key and signing method.
[hudx_report_sync@vnuchx7hudftpcl bin]$ s3cmd modify --acl-public --no-preserve --reduced-redundancy --recursive s3://mybucket/reports/conplans/ --debug &> problem.txt
```

[Here's the same, with `--debug`](https://gist.githubusercontent.com/jamiejackson/77f3aa91bf21deaf35c0/raw/log)

I guess one thing to note is that this is a DNS CNAME alias, so it's not `*.s3.amazonaws.com`. Not sure if that matters. (I just thought of it. I have to leave for the day, so can't test now.)

**Comment by jamiejackson** [comment] 2015-04-20 19:15
I don't claim to know why, but pull request #531 seems to fix the error I had, above.

**Comment by mdomsch** [comment] 2015-04-20 19:48
The one thing I do see is that the failed request had a "Connection: close"
header in it, where the others didn't...

**Comment by jamiejackson** [comment] 2015-04-20 21:18
Maybe I'll try playing with `ConnMan.conn_max_counter`, if I can manage to reproduce the issue as consistently as I had been before.

**Comment by jordie23** [comment] 2015-06-22 08:51
I had a very similar issue - couldn't work it out. Was using it to modify headers and worked fine for thousands of file, but would just stop at a certain point. Didn't seem to be a specific file. I changed S3/ConnMan.py `conn_max_counter = 800` to be `conn_max_counter = 80` and it worked.

**Comment by radeksimko** [comment] 2018-05-03 11:29
I can also reproduce this quite consistently with `conn_max_counter` set below `100`. Our deployment script which modifies headers for images in S3 via s3cmd started failing recently and I suspect it's because the number of images has grown which drove the number of requests/connections up.

I'll try to come up with a minimal repro case and I might potentially send a bugfix.

**Comment by fviard** [comment] 2018-05-03 14:05
@radeksimko a lot of things changed since this ticket was open.
Did you test with a recent version? best would be with the last github MASTER.

Also, you said that you modify the headers for the images, can you say what do you change as header exactly? The issue might come from special characters in the custom headers that are not encoded as they should.

**Comment by radeksimko** [comment] 2018-05-03 16:27
> Did you test with a recent version?

This is with [2.0.1 from Homebrew](https://github.com/Homebrew/homebrew-core/blob/d2ec1f44c4c8af7f5096e570968213ee1525b336/Formula/s3cmd.rb).

I have not tried last github master (yet).

> can you say what do you change as header exactly

see below

```
s3cmd \
    --mime-type="image/svg+xml" \
    --add-header="Cache-Control: max-age=31536000" \
    --exclude "*" \
    --include "*.svg" \
    --recursive \
    modify "s3://hc-sites/$PROJECT/latest/"
```
which returns exit code `2` (partial failure) after issuing `151` HTTP requests (counted via `grep 'DEBUG: Canonical Request:' stderr.log | wc -l`).

I was able to track down the failure (which seems to consistently point to the same file when retried) via `--debug`:
https://gist.github.com/radeksimko/03dbfdadf1eefc2b7d8ff1ac305abfbe (search for `Error`)

but I'm thinking it may be just coincidence given the current number of files and order of processing. There seems to be nothing special about that particular file and I'm able to run the exact same `s3cmd ... modify` command against that single file with success.

I noticed `DEBUG: ConnMan.put(): closing over-used connection` in the log.

I then tried re-uploading the exact same 37 SVG files into a brand new S3 bucket and run the exact same `modify` command, which was successful (although `DEBUG: ConnMan.put(): closing over-used connection` occured in the log too), which confuses me.

I'm now at the stage of comparing the two debug logs and trying to reproduce this in a new bucket.

**Comment by fviard** [comment] 2018-05-04 00:07
@radeksimko Thank for the debug log, I think that I know what is the issue and that @mdomsch was probably right in a very old comment.

When we do a modify, we first get the "headers" of the original file, and then kind of "update" the file metadata/headers with the modified headers.
For authorization, aws signature is based on a list of headers/values entries that we tell him that we have signed.

My guess is that for whatever reason it is aws that decided to end a connection after a reply sometimes, and so that "connection: close" end up in the returned headers. But on our side next connection/request, we will want "keep alive", so when the generated and received signed "headers" will be received, it will not match what aws could calculate.

Can you try a easy fix and tell me if it resolves your issue?
Edit the file: S3/S3.py
There is a function "_sanitize_headers(self, headers)".
Inside this function, you add
"connection" to the "to_remove" dictionnary.
(all in lower case).

Then, you tell me if you are still encountering your issue.

Thank you

**Comment by radeksimko** [comment] 2018-05-04 05:27
@fviard thanks, that helped 🎉 

I changed `conn_max_counter` back to `800` and did you you mentioned above and I can confirm it's working.

Here's a PR: https://github.com/s3tools/s3cmd/pull/970

**Closed** 2018-05-04 19:47 UTC

**Comment by fviard** [comment] 2018-05-04 19:49
@radeksimko merged!
Feels good to be able to close a bug that was mysterious for so long!
Thank you for the PR and for having investigated the issue!
