### ISSUE TITLE
put command doesn't always interpret "-" as stdin

### ISSUE THREAD

**Issue by coreyatmoat** [s3tools/s3cmd#562] opened 2015-06-05 19:31 UTC
Using 1.5.2:

```
$ BUCKET=search-archives
$ echo "12345" | s3cmd put - s3://${BUCKET}/test_keyname
<stdin> -> s3://search-archives/test_keyname  [part 1, 6B]
 6 of 6   100% in    0s   181.99 B/s  done
```

Working as expected. However, if you pipe that output to `cat`:

```
$ echo "12345" | s3cmd put - s3://${BUCKET}/test_keyname | cat
File '-' stored as 's3://search-archives/test_keyname' (0 bytes in 0.2 seconds, -1.00 B/s) [1 of 1]
```

it thinks you have a file named "-"

**Comment by fviard** [comment] 2018-03-04 14:26
Should be fixed, I can't reproduce anymore with 2.0.1

**Closed by fviard** 2018-03-04 14:26 UTC
