### ISSUE TITLE
Monitoring a S3 upload remotely

### ISSUE THREAD

**Issue by AbdulHadiParsdorfer** [s3tools/s3cmd#775] opened 2016-08-19 00:13 UTC
I want to use s3cmd for automatic video uploads after encoding.
I am planning to use Folder Actions on OSX to start the upload with a shell script after the encoding is finished.
Usually I leave the office after the encoding is started. Since I have to post the videos after the upload is finish I would like to check the progress from home to know when I can start with the posting. 

Is there a way to check the upload progress from home through a ssh connection?
How can I solve this problem?

Thank you.

**Comment by mdomsch** [comment] 2016-08-19 14:20
For situations like this, I use screen.  Start a screen instance, and start
s3cmd inside of screen.  You can then detach from the session, yet screen
keeps running.  You can re-attach to screen when you get home.  The whole
time the process continues to run inside of screen.

Thanks,
Matt

**Comment by AbdulHadiParsdorfer** [comment] 2016-08-22 00:56
Hi Matt,

thank you for the advice. The screen command is a great advice. Works very nice.
But I run in another problem. On my test machine I had an older version of s3cmd installed with homebrew.
Everything was working perfect with the old version.
After I installed the newest version of s3cmd on the other computer nothing could be upload anymore.
"([Errno 32] Broken pipe)
WARNING: Retrying on lower speed (throttle=0.01)”
I checked everything, tried everything what I could find in Google.
Finally I uninstalled the old version on my test computer and installed the same, newest version of s3cmd their.
With the result that I could not upload anything anymore.
"([Errno 32] Broken pipe)
WARNING: Retrying on lower speed (throttle=0.01)”

What is changed. Is something brocken in s3cmd?

Thank you.
Best Regards,

Robert

**Comment by fviard** [comment] 2016-08-22 14:40
Hi Robert,

Is it possible for you to send us a "debug log" ?
Please try to run s3cmd with the "-d" flag and paste us the output, or at least the most recent output near when it starts to "retry on lower speed".
Please take care to censor any "sensitive" value of your log.
Thank you

**Comment by fviard** [comment] 2016-08-22 14:41
And by the way, have you cross checked your configuration file to ensure that there was no change in it?
i would recommend you to try to generate a new config file with the new version also.

**Comment by AbdulHadiParsdorfer** [comment] 2016-08-22 18:01
Hi Florent,

I tried this as well. I checked and dumped the configuration and generated a new one.
Thank you.

**Comment by AbdulHadiParsdorfer** [comment] 2016-08-22 18:09
Hi Florent,

thank you for your answer. The sync command is working. No brocken pipe with sync. Here is the brocken pipe output from the put command:

shahmardan:CloudStation video$ s3cmd put -d --acl-public -m video/mp4 --add-header=Cache-Control:public,max-age=2052000 1989-08-00_en_MyShaykh_SN_a-Test.mp4 s3://saltanat-test/1989-08-00_en_MyShaykh_SN_a-Test.mp4
DEBUG: s3cmd version 1.6.1
DEBUG: ConfigParser: Reading file '/Users/video/.s3cfg'
DEBUG: ConfigParser: access_key->AK...17_chars...A
DEBUG: ConfigParser: access_token->
DEBUG: ConfigParser: add_encoding_exts->
DEBUG: ConfigParser: add_headers->
DEBUG: ConfigParser: bucket_location->EU
DEBUG: ConfigParser: ca_certs_file->
DEBUG: ConfigParser: cache_file->
DEBUG: ConfigParser: check_ssl_certificate->True
DEBUG: ConfigParser: check_ssl_hostname->True
DEBUG: ConfigParser: cloudfront_host->cloudfront.amazonaws.com
DEBUG: ConfigParser: default_mime_type->binary/octet-stream
DEBUG: ConfigParser: delay_updates->False
DEBUG: ConfigParser: delete_after->False
DEBUG: ConfigParser: delete_after_fetch->False
DEBUG: ConfigParser: delete_removed->False
DEBUG: ConfigParser: dry_run->False
DEBUG: ConfigParser: enable_multipart->True
DEBUG: ConfigParser: encoding->UTF-8
DEBUG: ConfigParser: encrypt->False
DEBUG: ConfigParser: expiry_date->
DEBUG: ConfigParser: expiry_days->
DEBUG: ConfigParser: expiry_prefix->
DEBUG: ConfigParser: follow_symlinks->False
DEBUG: ConfigParser: force->False
DEBUG: ConfigParser: get_continue->False
DEBUG: ConfigParser: gpg_command->None
DEBUG: ConfigParser: gpg_decrypt->%(gpg_command)s -d --verbose --no-use-agent --batch --yes --passphrase-fd %(passphrase_fd)s -o %(output_file)s %(input_file)s
DEBUG: ConfigParser: gpg_encrypt->%(gpg_command)s -c --verbose --no-use-agent --batch --yes --passphrase-fd %(passphrase_fd)s -o %(output_file)s %(input_file)s
DEBUG: ConfigParser: gpg_passphrase->...-3_chars...
DEBUG: ConfigParser: guess_mime_type->True
DEBUG: ConfigParser: host_base->s3.amazonaws.com
DEBUG: ConfigParser: host_bucket->%(bucket)s.s3.amazonaws.com
DEBUG: ConfigParser: human_readable_sizes->False
DEBUG: ConfigParser: invalidate_default_index_on_cf->False
DEBUG: ConfigParser: invalidate_default_index_root_on_cf->True
DEBUG: ConfigParser: invalidate_on_cf->False
DEBUG: ConfigParser: kms_key->
DEBUG: ConfigParser: limitrate->0
DEBUG: ConfigParser: list_md5->False
DEBUG: ConfigParser: log_target_prefix->
DEBUG: ConfigParser: long_listing->False
DEBUG: ConfigParser: max_delete->-1
DEBUG: ConfigParser: mime_type->
DEBUG: ConfigParser: multipart_chunk_size_mb->15
DEBUG: ConfigParser: multipart_max_chunks->10000
DEBUG: ConfigParser: preserve_attrs->True
DEBUG: ConfigParser: progress_meter->True
DEBUG: ConfigParser: proxy_host->
DEBUG: ConfigParser: proxy_port->0
DEBUG: ConfigParser: put_continue->False
DEBUG: ConfigParser: recursive->False
DEBUG: ConfigParser: recv_chunk->65536
DEBUG: ConfigParser: reduced_redundancy->False
DEBUG: ConfigParser: requester_pays->False
DEBUG: ConfigParser: restore_days->1
DEBUG: ConfigParser: secret_key->gH...37_chars...9
DEBUG: ConfigParser: send_chunk->65536
DEBUG: ConfigParser: server_side_encryption->False
DEBUG: ConfigParser: signature_v2->False
DEBUG: ConfigParser: simpledb_host->sdb.amazonaws.com
DEBUG: ConfigParser: skip_existing->False
DEBUG: ConfigParser: socket_timeout->300
DEBUG: ConfigParser: stats->False
DEBUG: ConfigParser: stop_on_error->False
DEBUG: ConfigParser: storage_class->
DEBUG: ConfigParser: urlencoding_mode->normal
DEBUG: ConfigParser: use_https->True
DEBUG: ConfigParser: use_mime_magic->True
DEBUG: ConfigParser: verbosity->WARNING
DEBUG: ConfigParser: website_endpoint->http://%(bucket)s.s3-website-%(location)s.amazonaws.com/
DEBUG: ConfigParser: website_error->
DEBUG: ConfigParser: website_index->index.html
DEBUG: Updating Config.Config extra_headers[cache-control] -> public,max-age=2052000
DEBUG: Updating Config.Config cache_file -> 
DEBUG: Updating Config.Config follow_symlinks -> False
DEBUG: Updating Config.Config mime_type -> video/mp4
DEBUG: Updating Config.Config verbosity -> 10
DEBUG: Unicodising 'put' using UTF-8
DEBUG: Unicodising '1989-08-00_en_MyShaykh_SN_a-Test.mp4' using UTF-8
DEBUG: Unicodising 's3://saltanat-test/1989-08-00_en_MyShaykh_SN_a-Test.mp4' using UTF-8
DEBUG: Command: put
DEBUG: DeUnicodising u'1989-08-00_en_MyShaykh_SN_a-Test.mp4' using UTF-8
INFO: Compiling list of local files...
DEBUG: DeUnicodising u'1989-08-00_en_MyShaykh_SN_a-Test.mp4' using UTF-8
DEBUG: DeUnicodising u'1989-08-00_en_MyShaykh_SN_a-Test.mp4' using UTF-8
DEBUG: Unicodising '' using UTF-8
DEBUG: DeUnicodising u'1989-08-00_en_MyShaykh_SN_a-Test.mp4' using UTF-8
DEBUG: DeUnicodising u'1989-08-00_en_MyShaykh_SN_a-Test.mp4' using UTF-8
DEBUG: Applying --exclude/--include
DEBUG: CHECK: 1989-08-00_en_MyShaykh_SN_a-Test.mp4
DEBUG: PASS: u'1989-08-00_en_MyShaykh_SN_a-Test.mp4'
INFO: Running stat() and reading/calculating MD5 values on 1 files, this may take some time...
DEBUG: DeUnicodising u'1989-08-00_en_MyShaykh_SN_a-Test.mp4' using UTF-8
DEBUG: doing file I/O to read md5 of 1989-08-00_en_MyShaykh_SN_a-Test.mp4
DEBUG: DeUnicodising u'1989-08-00_en_MyShaykh_SN_a-Test.mp4' using UTF-8
INFO: Summary: 1 local files to upload
DEBUG: attr_header: {'x-amz-meta-s3cmd-attrs': 'uid:501/gname:staff/uname:video/gid:20/mode:33188/mtime:1470850864/atime:1471888382/md5:d2e41e3f33be73716bde34d53bece66c/ctime:1471807544'}
DEBUG: DeUnicodising u'1989-08-00_en_MyShaykh_SN_a-Test.mp4' using UTF-8
DEBUG: DeUnicodising u'1989-08-00_en_MyShaykh_SN_a-Test.mp4' using UTF-8
DEBUG: DeUnicodising u'1989-08-00_en_MyShaykh_SN_a-Test.mp4' using UTF-8
DEBUG: String '1989-08-00_en_MyShaykh_SN_a-Test.mp4' encoded to '1989-08-00_en_MyShaykh_SN_a-Test.mp4'
DEBUG: CreateRequest: resource[uri]=/1989-08-00_en_MyShaykh_SN_a-Test.mp4
DEBUG: Using signature v4
DEBUG: get_hostname(saltanat-test): saltanat-test.s3.amazonaws.com
DEBUG: canonical_headers = cache-control:public,max-age=2052000
content-length:4158525
content-type:video/mp4
host:saltanat-test.s3.amazonaws.com
x-amz-acl:public-read
x-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date:20160822T175710Z
x-amz-meta-s3cmd-attrs:uid:501/gname:staff/uname:video/gid:20/mode:33188/mtime:1470850864/atime:1471888382/md5:d2e41e3f33be73716bde34d53bece66c/ctime:1471807544
x-amz-storage-class:STANDARD

DEBUG: Canonical Request:
PUT
/1989-08-00_en_MyShaykh_SN_a-Test.mp4

cache-control:public,max-age=2052000
content-length:4158525
content-type:video/mp4
host:saltanat-test.s3.amazonaws.com
x-amz-acl:public-read
x-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date:20160822T175710Z
x-amz-meta-s3cmd-attrs:uid:501/gname:staff/uname:video/gid:20/mode:33188/mtime:1470850864/atime:1471888382/md5:d2e41e3f33be73716bde34d53bece66c/ctime:1471807544
x-amz-storage-class:STANDARD

cache-control;content-length;content-type;host;x-amz-acl;x-amz-content-sha256;x-amz-date;x-amz-meta-s3cmd-attrs;x-amz-storage-class
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
----------------------
DEBUG: signature-v4 headers: {'x-amz-content-sha256': 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855', 'content-length': '4158525', 'x-amz-acl': 'public-read', 'x-amz-storage-class': 'STANDARD', 'x-amz-meta-s3cmd-attrs': 'uid:501/gname:staff/uname:video/gid:20/mode:33188/mtime:1470850864/atime:1471888382/md5:d2e41e3f33be73716bde34d53bece66c/ctime:1471807544', 'x-amz-date': '20160822T175710Z', 'cache-control': 'public,max-age=2052000', 'content-type': 'video/mp4', 'Authorization': 'AWS4-HMAC-SHA256 Credential=***********/20160822/EU/s3/aws4_request,SignedHeaders=cache-control;content-length;content-type;host;x-amz-acl;x-amz-content-sha256;x-amz-date;x-amz-meta-s3cmd-attrs;x-amz-storage-class,Signature=6578b7d83efcf20f9dc27ab21075ed776351ee5ea3ab9b8a95daca5886d47ce3'}
DEBUG: Unicodising '1989-08-00_en_MyShaykh_SN_a-Test.mp4' using UTF-8
upload: '1989-08-00_en_MyShaykh_SN_a-Test.mp4' -> 's3://saltanat-test/1989-08-00_en_MyShaykh_SN_a-Test.mp4'  [1 of 1]
DEBUG: DeUnicodising u'1989-08-00_en_MyShaykh_SN_a-Test.mp4' using UTF-8
DEBUG: Using signature v4
DEBUG: get_hostname(saltanat-test): saltanat-test.s3.amazonaws.com
DEBUG: canonical_headers = cache-control:public,max-age=2052000
content-length:4158525
content-type:video/mp4
host:saltanat-test.s3.amazonaws.com
x-amz-acl:public-read
x-amz-content-sha256:90b9f59db68744ecb1f5c86eaf76e86e259190a8446118e2686a2f101384e59f
x-amz-date:20160822T175710Z
x-amz-meta-s3cmd-attrs:uid:501/gname:staff/uname:video/gid:20/mode:33188/mtime:1470850864/atime:1471888382/md5:d2e41e3f33be73716bde34d53bece66c/ctime:1471807544
x-amz-storage-class:STANDARD

DEBUG: Canonical Request:
PUT
/1989-08-00_en_MyShaykh_SN_a-Test.mp4

cache-control:public,max-age=2052000
content-length:4158525
content-type:video/mp4
host:saltanat-test.s3.amazonaws.com
x-amz-acl:public-read
x-amz-content-sha256:90b9f59db68744ecb1f5c86eaf76e86e259190a8446118e2686a2f101384e59f
x-amz-date:20160822T175710Z
x-amz-meta-s3cmd-attrs:uid:501/gname:staff/uname:video/gid:20/mode:33188/mtime:1470850864/atime:1471888382/md5:d2e41e3f33be73716bde34d53bece66c/ctime:1471807544
x-amz-storage-class:STANDARD

cache-control;content-length;content-type;host;x-amz-acl;x-amz-content-sha256;x-amz-date;x-amz-meta-s3cmd-attrs;x-amz-storage-class
90b9f59db68744ecb1f5c86eaf76e86e259190a8446118e2686a2f101384e59f
----------------------
DEBUG: signature-v4 headers: {'x-amz-content-sha256': '90b9f59db68744ecb1f5c86eaf76e86e259190a8446118e2686a2f101384e59f', 'content-length': '4158525', 'x-amz-acl': 'public-read', 'x-amz-storage-class': 'STANDARD', 'x-amz-meta-s3cmd-attrs': 'uid:501/gname:staff/uname:video/gid:20/mode:33188/mtime:1470850864/atime:1471888382/md5:d2e41e3f33be73716bde34d53bece66c/ctime:1471807544', 'x-amz-date': '20160822T175710Z', 'cache-control': 'public,max-age=2052000', 'content-type': 'video/mp4', 'Authorization': 'AWS4-HMAC-SHA256 Credential=******************/20160822/EU/s3/aws4_request,SignedHeaders=cache-control;content-length;content-type;host;x-amz-acl;x-amz-content-sha256;x-amz-date;x-amz-meta-s3cmd-attrs;x-amz-storage-class,Signature=cb15d5f81730e850addf319dee5813d7c16f1899bd26c9a81cae2e9e927ccc95'}
DEBUG: get_hostname(saltanat-test): saltanat-test.s3.amazonaws.com
DEBUG: ConnMan.get(): creating new connection: https://saltanat-test.s3.amazonaws.com
DEBUG: Using ca_certs_file None
DEBUG: Recognized AWS S3 host, disabling initial SSL hostname check
DEBUG: httplib.HTTPSConnection() has only context
DEBUG: non-proxied HTTPSConnection(saltanat-test.s3.amazonaws.com)
DEBUG: format_uri(): /1989-08-00_en_MyShaykh_SN_a-Test.mp4
 1703936 of 4158525    40% in   16s   102.44 kB/s  failed
WARNING: Upload failed: /1989-08-00_en_MyShaykh_SN_a-Test.mp4 ([Errno 32] Broken pipe)
WARNING: Retrying on lower speed (throttle=0.00)
WARNING: Waiting 3 sec...
DEBUG: Using signature v4
DEBUG: get_hostname(saltanat-test): saltanat-test.s3.amazonaws.com
DEBUG: canonical_headers = cache-control:public,max-age=2052000
content-length:4158525
content-type:video/mp4
host:saltanat-test.s3.amazonaws.com
x-amz-acl:public-read
x-amz-content-sha256:90b9f59db68744ecb1f5c86eaf76e86e259190a8446118e2686a2f101384e59f
x-amz-date:20160822T175730Z
x-amz-meta-s3cmd-attrs:uid:501/gname:staff/uname:video/gid:20/mode:33188/mtime:1470850864/atime:1471888382/md5:d2e41e3f33be73716bde34d53bece66c/ctime:1471807544
x-amz-storage-class:STANDARD

DEBUG: Canonical Request:
PUT
/1989-08-00_en_MyShaykh_SN_a-Test.mp4

cache-control:public,max-age=2052000
content-length:4158525
content-type:video/mp4
host:saltanat-test.s3.amazonaws.com
x-amz-acl:public-read
x-amz-content-sha256:90b9f59db68744ecb1f5c86eaf76e86e259190a8446118e2686a2f101384e59f
x-amz-date:20160822T175730Z
x-amz-meta-s3cmd-attrs:uid:501/gname:staff/uname:video/gid:20/mode:33188/mtime:1470850864/atime:1471888382/md5:d2e41e3f33be73716bde34d53bece66c/ctime:1471807544
x-amz-storage-class:STANDARD

cache-control;content-length;content-type;host;x-amz-acl;x-amz-content-sha256;x-amz-date;x-amz-meta-s3cmd-attrs;x-amz-storage-class
90b9f59db68744ecb1f5c86eaf76e86e259190a8446118e2686a2f101384e59f
----------------------
DEBUG: signature-v4 headers: {'x-amz-content-sha256': '90b9f59db68744ecb1f5c86eaf76e86e259190a8446118e2686a2f101384e59f', 'content-length': '4158525', 'x-amz-acl': 'public-read', 'x-amz-storage-class': 'STANDARD', 'x-amz-meta-s3cmd-attrs': 'uid:501/gname:staff/uname:video/gid:20/mode:33188/mtime:1470850864/atime:1471888382/md5:d2e41e3f33be73716bde34d53bece66c/ctime:1471807544', 'x-amz-date': '20160822T175730Z', 'cache-control': 'public,max-age=2052000', 'content-type': 'video/mp4', 'Authorization': 'AWS4-HMAC-SHA256 Credential=*********************/20160822/EU/s3/aws4_request,SignedHeaders=cache-control;content-length;content-type;host;x-amz-acl;x-amz-content-sha256;x-amz-date;x-amz-meta-s3cmd-attrs;x-amz-storage-class,Signature=0baab6931d19c4cca4fa4bf553934e82579e989a661e72de4531f63620e49371'}
DEBUG: Unicodising '1989-08-00_en_MyShaykh_SN_a-Test.mp4' using UTF-8
upload: '1989-08-00_en_MyShaykh_SN_a-Test.mp4' -> 's3://saltanat-test/1989-08-00_en_MyShaykh_SN_a-Test.mp4'  [1 of 1]
DEBUG: DeUnicodising u'1989-08-00_en_MyShaykh_SN_a-Test.mp4' using UTF-8
DEBUG: Using signature v4
DEBUG: get_hostname(saltanat-test): saltanat-test.s3.amazonaws.com
DEBUG: canonical_headers = cache-control:public,max-age=2052000
content-length:4158525
content-type:video/mp4
host:saltanat-test.s3.amazonaws.com
x-amz-acl:public-read
x-amz-content-sha256:90b9f59db68744ecb1f5c86eaf76e86e259190a8446118e2686a2f101384e59f
x-amz-date:20160822T175730Z
x-amz-meta-s3cmd-attrs:uid:501/gname:staff/uname:video/gid:20/mode:33188/mtime:1470850864/atime:1471888382/md5:d2e41e3f33be73716bde34d53bece66c/ctime:1471807544
x-amz-storage-class:STANDARD

DEBUG: Canonical Request:
PUT
/1989-08-00_en_MyShaykh_SN_a-Test.mp4

cache-control:public,max-age=2052000
content-length:4158525
content-type:video/mp4
host:saltanat-test.s3.amazonaws.com
x-amz-acl:public-read
x-amz-content-sha256:90b9f59db68744ecb1f5c86eaf76e86e259190a8446118e2686a2f101384e59f
x-amz-date:20160822T175730Z
x-amz-meta-s3cmd-attrs:uid:501/gname:staff/uname:video/gid:20/mode:33188/mtime:1470850864/atime:1471888382/md5:d2e41e3f33be73716bde34d53bece66c/ctime:1471807544
x-amz-storage-class:STANDARD

cache-control;content-length;content-type;host;x-amz-acl;x-amz-content-sha256;x-amz-date;x-amz-meta-s3cmd-attrs;x-amz-storage-class
90b9f59db68744ecb1f5c86eaf76e86e259190a8446118e2686a2f101384e59f
----------------------
DEBUG: signature-v4 headers: {'x-amz-content-sha256': '90b9f59db68744ecb1f5c86eaf76e86e259190a8446118e2686a2f101384e59f', 'content-length': '4158525', 'x-amz-acl': 'public-read', 'x-amz-storage-class': 'STANDARD', 'x-amz-meta-s3cmd-attrs': 'uid:501/gname:staff/uname:video/gid:20/mode:33188/mtime:1470850864/atime:1471888382/md5:d2e41e3f33be73716bde34d53bece66c/ctime:1471807544', 'x-amz-date': '20160822T175730Z', 'cache-control': 'public,max-age=2052000', 'content-type': 'video/mp4', 'Authorization': 'AWS4-HMAC-SHA256 Credential=**********************/20160822/EU/s3/aws4_request,SignedHeaders=cache-control;content-length;content-type;host;x-amz-acl;x-amz-content-sha256;x-amz-date;x-amz-meta-s3cmd-attrs;x-amz-storage-class,Signature=0baab6931d19c4cca4fa4bf553934e82579e989a661e72de4531f63620e49371'}
DEBUG: get_hostname(saltanat-test): saltanat-test.s3.amazonaws.com
DEBUG: ConnMan.get(): creating new connection: https://saltanat-test.s3.amazonaws.com
DEBUG: Recognized AWS S3 host, disabling initial SSL hostname check
DEBUG: httplib.HTTPSConnection() has only context
DEBUG: non-proxied HTTPSConnection(saltanat-test.s3.amazonaws.com)
DEBUG: format_uri(): /1989-08-00_en_MyShaykh_SN_a-Test.mp4
 1703936 of 4158525    40% in   20s    82.34 kB/s  failed
WARNING: Upload failed: /1989-08-00_en_MyShaykh_SN_a-Test.mp4 ([Errno 32] Broken pipe)
WARNING: Retrying on lower speed (throttle=0.01)
WARNING: Waiting 6 sec...
^CSee ya!
shahmardan:CloudStation video$

**Comment by fviard** [comment] 2016-08-22 22:17
@AbdulHadiParsdorfer Thanks to your detailed report, I start to have some hypthesis about this issue that is regularly reported.
- Can you tell me the version of python that you are using (python --version) ? And the name/version of your linux distribution?
- Can you show me the output of : s3cmd info s3://saltanat-test/1989-08-00_en_MyShaykh_SN_a-Test.mp4

**Comment by AbdulHadiParsdorfer** [comment] 2016-08-23 14:48
Hi Florent,

thank you. 

1. Python 2.7.10; I am working on OSX 10.11.6;  s3cmd version 1.6.1 (Homebrew) 

2. s3cmd info s3://saltanat-test/1989-08-00_en_MyShaykh_SN_a-Test.mp4  >> output: S3 error: 404 (Not Found)
The file does not exist on s3.

3. output for another file uploaded with s3cmd sync command > s3cmd info s3://saltanat-test/ForAutomatorTest.mp4:

s3://saltanat-test/ForAutomatorTest.mp4 (object):
   File size: 6074630
   Last mod:  Tue, 23 Aug 2016 13:36:10 GMT
   MIME type: application/octet-stream
   Storage:   STANDARD
   MD5 sum:   d0f1f45396bea927bd512e4f2db7fb82
   SSE:       none
   policy:    none
   cors:      none
   ACL:       naqsh: FULL_CONTROL
   ACL:       *anon*: READ
   URL:       http://saltanat-test.s3.amazonaws.com/ForAutomatorTest.mp4
shahmardan:~ video$ s3cmd info s3://saltanat-test/ForAutomatorTest.mp4
s3://saltanat-test/ForAutomatorTest.mp4 (object):
   File size: 6074630
   Last mod:  Tue, 23 Aug 2016 14:44:13 GMT
   MIME type: video/mp4
   Storage:   STANDARD
   MD5 sum:   d0f1f45396bea927bd512e4f2db7fb82
   SSE:       none
   policy:    none
   cors:      none
   ACL:       naqsh: FULL_CONTROL
   ACL:       *anon*: READ
   URL:       http://saltanat-test.s3.amazonaws.com/ForAutomatorTest.mp4
   x-amz-meta-s3cmd-attrs: uid:504/gname:wheel/uname:abdulhadi/gid:0/mode:33206/mtime:1471733782/atime:1471959258/md5:d0f1f45396bea927bd512e4f2db7fb82/ctime:1471733782

**Comment by fviard** [comment] 2016-08-25 08:42
Thank you @AbdulHadiParsdorfer, with all the info that you have provided, I think that I have now a clue of the origin of this issue that appears regularly.
So far I'm not able to reproduce the issue, so I know that it is annoying, but if you are able to keep the setup that is failing, that could help us a lot find a fix for the issue.

Can you tell me in which country you are?

**Comment by AbdulHadiParsdorfer** [comment] 2016-08-25 20:05
Hi Florent,

I am happy if I can help you.
I am based in Cyprus but on the North Side. The Internet traffic from here goes first to Turkey.

**Comment by AbdulHadiParsdorfer** [comment] 2016-09-18 11:50
Hi Florent,

any news?
Thank you.

**Comment by fviard** [comment] 2016-11-15 09:54
This issue should now be fixed in master.
Please give it a try.

**Closed by fviard** 2016-11-15 09:54 UTC
Labels: to-be-fixed

**Comment by AbdulHadiParsdorfer** [comment] 2016-11-15 21:32
Thank you so much Florent. I tried it. Seems to work.

**Comment by AbdulHadiParsdorfer** [comment] 2016-12-18 17:32
Hi Florent, now I get very often following failure:
ERROR: S3 error: 400 (XAmzContentSHA256Mismatch): The provided 'x-amz-content-sha256' header does not match what was computed.
Is it related to the previous problem? Thank you.

**Comment by swq499809608** [comment] 2018-06-06 01:44
Unfortunately, I also encountered the same problem, I have 1000 small files in the current directory, using the s3cmd command upload error  


ERROR: S3 error: 400 (XAmzContentSHA256Mismatch)
