### ISSUE TITLE
Upload via Cloudfront

### ISSUE THREAD

**Issue by pctj101** [s3tools/s3cmd#254] opened 2013-12-08 06:04 UTC
I'm trying to upload a large amount of data via CloudFront into an S3 bucket (since Amazon CF now supports POST).  The idea is to of course, accelerate the uploads and use Amazon's optimized backbones rather than the route my ISP is sending my traffic through to the US East Coast.

However, in s3cmd, all our s3://urls don't really make it so obvious how we could upload via a different http end point such as http://whatever.cloudfont.net which would hopefully act via HTTP just like the original S3 end point.

In case I missed it, is there a good way to do this?  Or if I was to try to hack this in, has anyone already decided on a starting point that I should look into?

**Comment by fviard** [comment] 2023-10-22 23:05
Closing "not a bug" report. @brandongalbraith gave the correct response.

**Closed by fviard** 2023-10-22 23:05 UTC
Labels: not-a-bug
